# More exmaples of openfaas function here: https://github.com/openfaas/openfaas-operator
{{- if eq .Values.createFunction true }}
{{- if .Values.global.openfaas.enabled | default false | ne true }}
{{- required "`ckan-connector-functions` requires `magda-core`.`openfaas` to deploy. Please turn on openfaas by setting `global.openfaas.enabled` to `true` or turn off `ckan-connector-functions` to avoid this error." nil }}
{{- else }}
apiVersion: openfaas.com/v1
kind: Function
metadata:
  name: ckan-data-url-processor
  namespace: {{ include "magda-ckan-connector.openfaaFunctionNamespace" . | quote }}
  labels: 
    magdaCategory: connectors
    magdaSubCategory: ckan-connector
    magdaType: data-url-processor
spec:
  name: ckan-data-url-processor
  handler: node bootstrap.js
  image: {{ include "magda.image" . | quote }}
  labels: 
    magdaCategory: connectors
    magdaSubCategory: ckan-connector
    magdaType: data-url-processor
    com.openfaas.scale.zero: "true"
  annotations:
    com.openfaas.health.http.path: "/healthz"
    com.openfaas.health.http.initialDelay: "10s"
  environment:
    handler: remoteDataUrl
    read_timeout: 65s
    write_timeout: 65s
    exec_timeout: 60s
    userId: 00000000-0000-4000-8000-000000000000
  {{- $pullSecrets := include "magda.image.getConsolidatedPullSecretList" . | mustFromJson }}
  {{- if (not (empty $pullSecrets)) }}
  secrets: 
    {{- range $pullSecrets }}
    - {{ . | quote }}
    {{- end }}
  {{- end }}
{{ .Values.resources | toYaml | indent 2 -}}
{{- end }}
{{- end }}
