{{- if and .Values.openfaas .Values.openfaas.functionNamespace }}
apiVersion: openfaas.com/v1
kind: Function
metadata:
  name: ckan-data-url-processor
  namespace: {{ .Values.openfaas.functionNamespace | default "openfaas-fn" }}
  labels: 
    magda-category: connectors
    magda-sub-category: ckan-connector
    magda-type: data-url-processor
spec:
  name: ckan-data-url-processor
  handler: node bootstrap.js
  image: "{{ .Values.image.repository | default .Values.global.connectors.image.repository | default .Values.global.image.repository | default .Values.defaultImage.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag | default .Values.global.connectors.image.tag | default .Values.global.image.tag | default .Values.defaultImage.tag }}"
  labels: 
    magda-category: connectors
    magda-sub-category: ckan-connector
    magda-type: data-url-processor
  environment:
    handler: remoteDataUrl
    read_timeout: 65s
    write_timeout: 65s
    exec_timeout: 60s
    userId: 00000000-0000-4000-8000-000000000000
{{ .Values.resources | toYaml | indent 2 -}}
  secrets:
    - jwt-secret