name: Main CI Workflow

on: push

jobs:
  build-test-docker:
    name: Build, Test & Push to Docker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 10
      uses: actions/setup-node@v1
      with:
        node-version: 10
    - run: yarn install
    - run: yarn build
    - run: yarn test

    - name: helm-check
      run: helm lint ./deploy/charts/magda-ckan-connector -f ./deploy/test-deploy.yaml

    - name: Login to GitHub Package Repository
      env:
        GH_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      run: docker login docker.pkg.github.com -u magdabot -p ${GH_TOKEN}
      
    - name: Build Docker Image & Push 
      run: yarn docker-build-prod --repository=docker.pkg.github.com/magda-io/magda-ckan-connector --name=magda-ckan-connector --version=${GITHUB_SHA}
    
  build-test-node-8:
    name: Build, Test Only with Node 8
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 8
      uses: actions/setup-node@v1
      with:
        node-version: 8
    - run: yarn install
    - run: yarn build
    - run: yarn test


