name: CI Release Helm Chart

on:
  release:
    types: [published]

env:
  REPO_NAME: magda-ckan-connector

jobs:
  release-helm-chart:
    name: Release Helm Chart
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: yarn install
      - run: yarn build
      - run: yarn test

      - name: helm-build-dependencies
        run: helm dep up deploy/${REPO_NAME}

      - name: helm-check
        run: yarn helm-lint

      - name: helm-chart-version-check
        run: yarn check-helm-chart-version deploy/${REPO_NAME}/Chart.yaml

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Package Repository
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker Image & Push to Github Container Registry
        run: yarn docker-build-prod --repository=ghcr.io/${{ github.repository_owner }} --name=${REPO_NAME} --version=${GITHUB_SHA} --platform=linux/amd64,linux/arm64

      - name: Re-tag & Push Docker Image to Github Container Registry
        run: |
          PACKAGE_JSON_VERSION=$(jq -r ".version" package.json)
          chmod +r $HOME/.docker/config.json
          docker container run --rm --net host \
            -v regctl-conf:/home/appuser/.regctl/ \
            -v $HOME/.docker/config.json:/home/appuser/.docker/config.json \
            regclient/regctl:v0.4.5 image copy ghcr.io/${{ github.repository_owner }}/${REPO_NAME}:${GITHUB_SHA} ghcr.io/${REPO_OWNER}/${REPO_NAME}:${PACKAGE_JSON_VERSION}

      - name: Release Helm Chart
        run: |
          REPO_OWNER=`echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]'`
          cd deploy
          helm package ${REPO_NAME}
          PKG_NAME=`ls *.tgz`
          helm push ${PKG_NAME} oci://ghcr.io/${REPO_OWNER}/charts
